name: Deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          cd Abhishek_Krishna_A_M
          npm install
          npm run build
      - name: Deploy to GH Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          cd Abhishek_Krishna_A_M
          git add docs
          git commit -m "Deploy to GitHub Pages"
          git push
